In [27]:
import tensorflow as tf
import numpy as np 

In [3]:
tf.constant([1, 2, 3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [5]:
tf.constant([[1, 2, 3], [2, 0, 0]], dtype=tf.float32)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [2., 0., 0.]], dtype=float32)>

In [11]:
A = tf.constant([[1, 2, 3], [2, 3, 5]], dtype=tf.float32)

In [12]:
A + 1

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[2., 3., 4.],
       [3., 4., 6.]], dtype=float32)>

In [14]:
A[:, 1, tf.newaxis]

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [3.]], dtype=float32)>

In [15]:
A[0, :]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [25]:
tf.reduce_sum(A, axis=1, keepdims=True)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[ 6.],
       [10.]], dtype=float32)>

In [34]:
A.numpy()

array([[1., 2., 3.],
       [2., 3., 5.]], dtype=float32)

In [33]:
np.mean(A.numpy(), axis=0)

array([1.5, 2.5, 4. ], dtype=float32)

In [35]:
A = A + 1

In [36]:
A

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[2., 3., 4.],
       [3., 4., 6.]], dtype=float32)>