In [1]:
import keras
import tensorflow as tf

2024-04-23 16:06:10.532778: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-04-23 16:06:10.615767: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-04-23 16:06:10.615837: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-04-23 16:06:10.617753: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-04-23 16:06:10.631711: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-04-23 16:06:10.632480: I tensorflow/core/platform/cpu_feature_guard.cc:1

In [2]:
A = tf.constant(value=[[1,2,3],[1,2,3]])
A

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [1, 2, 3]], dtype=int32)>

In [3]:
B = tf.constant(value=[[1],[5],[3]])
B

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[1],
       [5],
       [3]], dtype=int32)>

In [4]:
A@B

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[20],
       [20]], dtype=int32)>

In [5]:
A[:,1], A[1,1]

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 2], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>)

In [6]:
A*10, A+11, tf.matmul(A,B)

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[10, 20, 30],
        [10, 20, 30]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[12, 13, 14],
        [12, 13, 14]], dtype=int32)>,
 <tf.Tensor: shape=(2, 1), dtype=int32, numpy=
 array([[20],
        [20]], dtype=int32)>)

In [7]:
tf.reduce_mean(B)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [8]:
import numpy as np

In [9]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [10]:
B = tf.constant(a)
B

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 2, 3, 4])>

In [11]:
tf.square(a)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([ 1,  4,  9, 16])>

In [18]:
a =  tf.constant(3.)

In [13]:
b = tf.constant(40)
b

<tf.Tensor: shape=(), dtype=int32, numpy=40>

In [14]:
try:
    print(a+b)
except Exception as e:
    print(e)
finally:
    pass

cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a int32 tensor [Op:AddV2] name: 


In [15]:
tf.constant(1, dtype=tf.float64) 

<tf.Tensor: shape=(), dtype=float64, numpy=1.0>

### Tf.variable 

In [28]:
A = tf.Variable(initial_value=[[1,2.],[2,1]], name='Array A')
A

<tf.Variable 'Array A:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [2., 1.]], dtype=float32)>

In [29]:
A[1,1].assign(-1)

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=float32, numpy=
array([[ 1.,  2.],
       [ 2., -1.]], dtype=float32)>